# Generated by Django 4.0 on 2022-01-20 14:20

import ckeditor.fields
import course.utilities.models_validatior
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blog', '0002_category_date_publish_post_date_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('detail', ckeditor.fields.RichTextField()),
                ('off', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(upload_to='course/image')),
                ('date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='content/image')),
                ('title', models.CharField(max_length=1024)),
                ('detail', ckeditor.fields.RichTextField()),
                ('video', models.FileField(upload_to='course/video', validators=[course.utilities.models_validatior.validate_video_extension])),
                ('date', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Commnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.CharField(max_length=1024)),
                ('date', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_comment', to='course.commnet')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_comment', to='course.commnet')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.user')),
            ],
        ),
    ]
