# Generated by Django 4.0 on 2022-03-29 11:46

import ckeditor.fields
import course.utilities.models_validatior
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='card',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='content',
            name='course',
        ),
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('FR', 'FREEZE'), ('PD', 'PAID'), ('IP', 'INPROCESS')], default='IP', max_length=2),
        ),
        migrations.AddField(
            model_name='course',
            name='desribe_video',
            field=models.FileField(blank=True, null=True, upload_to='course/video', validators=[course.utilities.models_validatior.validate_video_extension]),
        ),
        migrations.AlterField(
            model_name='content',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='content/video', validators=[course.utilities.models_validatior.validate_video_extension]),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('detail', ckeditor.fields.RichTextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.season'),
            preserve_default=False,
        ),
    ]
