# Generated by Django 4.0 on 2022-04-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_card_is_finished_remove_card_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_promote',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Commnet',
        ),
    ]
