# Generated by Django 4.0 on 2022-02-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_expire',
            field=models.BooleanField(default=False),
        ),
    ]
