# Generated by Django 4.0 on 2022-02-11 14:30

import ckeditor.fields
import course.utilities.models_validatior
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_is_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commnet',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='content/image'),
        ),
        migrations.AlterField(
            model_name='content',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='course/video', validators=[course.utilities.models_validatior.validate_video_extension]),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course/image'),
        ),
    ]
