# Generated by Django 4.0 on 2022-04-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_is_promote_delete_commnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='', upload_to='course/image'),
            preserve_default=False,
        ),
    ]
