# Generated by Django 4.0 on 2022-02-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_delete_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='courses',
            field=models.ManyToManyField(blank=True, to='course.Course'),
        ),
    ]
