# Generated by Django 4.0 on 2022-04-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_card_time_change_status_card_time_created'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'IP'), ('status', 'FR'), _connector='OR'), fields=('user',), name='unique_active_card'),
        ),
    ]
