# Generated by Django 4.0 on 2022-04-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_card_unique_active_card'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='card',
            name='unique_active_card',
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'IP')), fields=('user',), name='unique_active_ip_card'),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'FR')), fields=('user',), name='unique_active_fr_card'),
        ),
    ]
