# Generated by Django 4.0 on 2022-04-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_remove_card_unique_active_card_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='card',
            name='unique_active_ip_card',
        ),
        migrations.RemoveConstraint(
            model_name='card',
            name='unique_active_fr_card',
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'IP'), ('status', 'FR'), _connector='OR'), fields=('user',), name='unique_active_card'),
        ),
    ]
