# Generated by Django 4.0 on 2022-04-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_course_supported_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='buy_counter',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
