# Generated by Django 3.2.13 on 2022-04-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_course_buy_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='supported_course',
            field=models.ManyToManyField(blank=True, related_name='_course_course_supported_course_+', to='course.Course'),
        ),
    ]
