# Generated by Django 3.2.13 on 2022-04-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_alter_course_supported_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_counter_added_to_courses',
            field=models.BooleanField(default=False),
        ),
    ]
