# Generated by Django 3.2.13 on 2022-04-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_card_is_counter_added_to_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='is_counter_added_to_courses',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
