# Generated by Django 4.0 on 2022-01-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_publish',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='date_publish',
            field=models.DateField(auto_now=True),
        ),
    ]
