# Generated by Django 3.2.13 on 2022-04-25 17:42

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_date_publish_alter_video_date_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_color',
            field=colorfield.fields.ColorField(default='#3d8835', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=colorfield.fields.ColorField(default='#88153e', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='category',
            name='text_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=None),
        ),
    ]
