# Generated by Django 4.0 on 2022-04-10 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('off', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('name', models.CharField(max_length=256, unique=True, validators=[django.core.validators.RegexValidator(' ', 'No spaces allowed', code='invalid_tag', inverse_match=True)])),
            ],
        ),
    ]
