# Generated by Django 4.0 on 2022-02-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zarinpal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='amount',
            field=models.PositiveBigIntegerField(),
        ),
    ]
