# Generated by Django 4.0 on 2022-04-10 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zarinpal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='time_tr',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
