# Generated by Django 4.0 on 2022-02-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zarinpal', '0003_pay_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='authority',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
