# Generated by Django 4.0 on 2022-02-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zarinpal', '0004_pay_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='authority',
            field=models.TextField(blank=True, null=True),
        ),
    ]
