from mahpen.settings import ZARINPAL_CONFIGURATION

MMERCHANT_ID = ZARINPAL_CONFIGURATION.get("merchant_id")
ZARINPAL_WEBSERVICE = ZARINPAL_CONFIGURATION.get("zarinpal_webservice")
DESCRIPTION = ZARINPAL_CONFIGURATION.get("description")
CALL_BACK_URL = ZARINPAL_CONFIGURATION.get("call_back_url")
START_PAY = ZARINPAL_CONFIGURATION.get("start_pay")